// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ServiceRequestMS.data.Data;

#nullable disable

namespace ServiceRequestMS.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ServiceRequestMS.Core.Models.Request", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AssignedStaffId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("LastUpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LastUpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AssignedStaffId");

                    b.HasIndex("CategoryItemId");

                    b.HasIndex("CreatedBy");

                    b.ToTable("Requests");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5181c457-cf0c-4538-921b-d56e71550a63"),
                            CategoryItemId = new Guid("d1111111-1111-1111-1111-111111111111"),
                            CreatedBy = new Guid("33333333-3333-3333-3333-333333333333"),
                            CreatedDate = new DateTime(2026, 4, 4, 23, 52, 40, 847, DateTimeKind.Local).AddTicks(7042),
                            Description = "Left click is not responding",
                            Status = "New",
                            Title = "Broken Mouse"
                        },
                        new
                        {
                            Id = new Guid("49afc61e-4e67-4a22-aa88-c80689164a4d"),
                            AssignedStaffId = new Guid("44444444-4444-4444-4444-444444444444"),
                            CategoryItemId = new Guid("d2222222-2222-2222-2222-222222222222"),
                            CreatedBy = new Guid("33333333-3333-3333-3333-333333333333"),
                            CreatedDate = new DateTime(2026, 4, 4, 21, 52, 40, 847, DateTimeKind.Local).AddTicks(7048),
                            Description = "Monitor screen keeps turning off",
                            Status = "Assigned",
                            Title = "Screen Flickering"
                        },
                        new
                        {
                            Id = new Guid("d531c9f1-0ae9-407d-bf2e-d7a6316b41b9"),
                            AssignedStaffId = new Guid("44444444-4444-4444-4444-444444444444"),
                            CategoryItemId = new Guid("d3333333-3333-3333-3333-333333333333"),
                            CreatedBy = new Guid("33333333-3333-3333-3333-333333333333"),
                            CreatedDate = new DateTime(2026, 4, 3, 23, 52, 40, 847, DateTimeKind.Local).AddTicks(7059),
                            Description = "Need to activate Windows 11",
                            Status = "InProgress",
                            Title = "Windows Activation"
                        });
                });

            modelBuilder.Entity("ServiceRequestMS.core.Models.Attachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("LastUpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LastUpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RequestId");

                    b.HasIndex("UserId");

                    b.ToTable("Attachments");
                });

            modelBuilder.Entity("ServiceRequestMS.core.Models.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("LastUpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LastUpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatedDate = new DateTime(2026, 4, 4, 23, 52, 40, 847, DateTimeKind.Local).AddTicks(6863),
                            Description = "Physical devices and equipment",
                            Name = "Hardware"
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatedDate = new DateTime(2026, 4, 4, 23, 52, 40, 847, DateTimeKind.Local).AddTicks(6866),
                            Description = "Applications and licenses",
                            Name = "Software"
                        });
                });

            modelBuilder.Entity("ServiceRequestMS.core.Models.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CommentText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("LastUpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LastUpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RequestId");

                    b.HasIndex("UserId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("ServiceRequestMS.core.Models.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("LastUpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LastUpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d1111111-1111-1111-1111-111111111111"),
                            CategoryId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatedDate = new DateTime(2026, 4, 4, 23, 52, 40, 847, DateTimeKind.Local).AddTicks(6895),
                            Description = "Pointing devices",
                            Name = "Mouse"
                        },
                        new
                        {
                            Id = new Guid("d2222222-2222-2222-2222-222222222222"),
                            CategoryId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatedDate = new DateTime(2026, 4, 4, 23, 52, 40, 847, DateTimeKind.Local).AddTicks(6947),
                            Description = "Display screens",
                            Name = "Monitor"
                        },
                        new
                        {
                            Id = new Guid("d3333333-3333-3333-3333-333333333333"),
                            CategoryId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatedDate = new DateTime(2026, 4, 4, 23, 52, 40, 847, DateTimeKind.Local).AddTicks(6950),
                            Description = "OS Activation",
                            Name = "Windows License"
                        });
                });

            modelBuilder.Entity("ServiceRequestMS.core.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid?>("LastUpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LastUpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatedDate = new DateTime(2026, 4, 4, 23, 52, 40, 847, DateTimeKind.Local).AddTicks(6640),
                            Email = "",
                            FullName = "System Admin",
                            IsActive = true,
                            PasswordHash = "123",
                            PhoneNumber = "",
                            Role = "Admin",
                            UserName = "admin"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatedDate = new DateTime(2026, 4, 4, 23, 52, 40, 847, DateTimeKind.Local).AddTicks(6666),
                            Email = "",
                            FullName = "Project Manager",
                            IsActive = true,
                            PasswordHash = "123",
                            PhoneNumber = "",
                            Role = "Manager",
                            UserName = "manager"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatedDate = new DateTime(2026, 4, 4, 23, 52, 40, 847, DateTimeKind.Local).AddTicks(6670),
                            Email = "",
                            FullName = "Ahmad Employee",
                            IsActive = true,
                            PasswordHash = "123",
                            PhoneNumber = "",
                            Role = "Employee",
                            UserName = "ahmad"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatedDate = new DateTime(2026, 4, 4, 23, 52, 40, 847, DateTimeKind.Local).AddTicks(6673),
                            Email = "",
                            FullName = "Tech Staff",
                            IsActive = true,
                            PasswordHash = "123",
                            PhoneNumber = "",
                            Role = "Staff",
                            UserName = "staff"
                        });
                });

            modelBuilder.Entity("ServiceRequestMS.Core.Models.Request", b =>
                {
                    b.HasOne("ServiceRequestMS.core.Models.User", "AssignedStaff")
                        .WithMany("AssignedRequests")
                        .HasForeignKey("AssignedStaffId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ServiceRequestMS.core.Models.Item", "CategoryItem")
                        .WithMany("Requests")
                        .HasForeignKey("CategoryItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ServiceRequestMS.core.Models.User", "Requester")
                        .WithMany("CreatedRequests")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AssignedStaff");

                    b.Navigation("CategoryItem");

                    b.Navigation("Requester");
                });

            modelBuilder.Entity("ServiceRequestMS.core.Models.Attachment", b =>
                {
                    b.HasOne("ServiceRequestMS.Core.Models.Request", "Request")
                        .WithMany("Attachments")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ServiceRequestMS.core.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Request");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ServiceRequestMS.core.Models.Comment", b =>
                {
                    b.HasOne("ServiceRequestMS.Core.Models.Request", "Request")
                        .WithMany("Comments")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ServiceRequestMS.core.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Request");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ServiceRequestMS.core.Models.Item", b =>
                {
                    b.HasOne("ServiceRequestMS.core.Models.Category", "Category")
                        .WithMany("Items")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ServiceRequestMS.Core.Models.Request", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("Comments");
                });

            modelBuilder.Entity("ServiceRequestMS.core.Models.Category", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("ServiceRequestMS.core.Models.Item", b =>
                {
                    b.Navigation("Requests");
                });

            modelBuilder.Entity("ServiceRequestMS.core.Models.User", b =>
                {
                    b.Navigation("AssignedRequests");

                    b.Navigation("CreatedRequests");
                });
#pragma warning restore 612, 618
        }
    }
}
